from pprint import pprint
from RNA.codon_reader import CodonReader
from RNA.amino_acid_codons import ALL_ACIDS
from RNA.splicing.spliceosome import Spliceosome
from RNA.insulin import INS

reader = CodonReader(ALL_ACIDS)

string = 'ATGGTGCACCTGACTGATGCTGAGAAGGCTGCTGTCTCTGGCCTGTGGGGAAAGGTGAACGCCGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTTGTCTACCCTTGGACCCAGCGGTACTTTGATAGCTTTGGAGACCTATCCTCTGCCTCTGCTATCATGGGTAATGCCAAAGTGAAGGCCCATGGCAAGAAAGTGATAACTGCCTTTAACGATGGCCTGAATCACTTGGACAGCCTCAAGGGCACCTTTGCCAGCCTCAGTGAGCTCCACTGTGACAAGCTGCATGTGGATCCTGAGAACTTCAGGCTCCTGGGCAATATGATCGTGATTGTGCTGGGCCACCACCTGGGCAAGGATTTCACCCCCGCTGCACAGGCTGCCTTCCAGAAGGTGGTGGCTGGAGTGGCCGCTGCCCTGGCTCACAAGTACCACTAA'

acid_chain = reader.translate_string(string.replace('T', 'U'))

l = list(acid_chain)

EXPECTED_CODING_SEQUENCE = 'ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAG'\
    .replace('T', 'U')

print('expected translation', ''.join([blah.pattern.abbr for blah in reader.translate_string(EXPECTED_CODING_SEQUENCE)]))

s = Spliceosome()


spliced = list(s.splice(INS.replace('T', 'U')))

poly_peptide_chain = list(reader.translate_exons(spliced))

print(poly_peptide_chain)
print(''.join([blah.pattern.abbr for blah in poly_peptide_chain]))